### ISSUE TITLE
下载后，运行不了

### ISSUE THREAD

**Issue by Cuiqs76** [seven1986/IdentityServer4.MicroService.AdminUI#1]
下载后，运行不了，浏览器显示：
找不到 localhost 的网页
找不到与以下网址对应的网页：http://localhost:61714/
HTTP ERROR 404
系统： windows 10
IDE:  VS 2017
node: 9.8.0 

请问能否简单介绍一下如何配置启动？

**Comment by seven1986** [comment]
你好，该UI项目计划将自动集成到【IdentityServer4Microservice】Nuget包里
